apiVersion: batch/v1
kind: Job
metadata:
  name: presync-hooks
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded   
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Migrating Database"
            echo "Migration successfull"
      restartPolicy: Never
