apiVersion: v1
kind: LimitRange
metadata:
  name: app1-limitrange
  namespace: app1-ns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
